# Code written from section 2.4

In [14]:
from numpy import zeros, array, dot

### Numpy Zero Array Example

In [2]:
a = zeros(4, float)
print(a)

[ 0.  0.  0.  0.]


### 2-Dim Array with addition and dot product examples

In [18]:
a = array([[1,2,3],[4,5,6]],int)
print("a\n",a)
b = array([[1,2,3],[4,5,6]],int)
print("\nb\n",b)
print("\na+b\n",a+b)
a = array([1,2,3,4,5,6],int)
print("a\n",a)
b = array([1,2,3,4,5,6],int)
print("\nb\n",b)
print("\na dot b: ",dot(a,b))

a
 [[1 2 3]
 [4 5 6]]

b
 [[1 2 3]
 [4 5 6]]

a+b
 [[ 2  4  6]
 [ 8 10 12]]
a
 [1 2 3 4 5 6]

b
 [1 2 3 4 5 6]

a dot b:  91


### Lambda Notation on Array

In [29]:
from math import sqrt
import numpy as np

def sqr(x): 
    return x ** 2

a = np.array([1,2,3,4,5,6],float)
# not sure why not working, but same exact example in book on page 2.4
# could be that using 3.x instead of 2.x
b = np.array(map(sqr,a), float)
print(b)

TypeError: float() argument must be a string or a number, not 'map'

### Example using loadtxt

In [2]:
from numpy import loadtxt
values = loadtxt("file.txt", int)
mean = sum(value)/len(values)
print(mean)

FileNotFoundError: [Errno 2] No such file or directory: 'file.txt'

### Geometric mean from textfile example

In [36]:
from numpy import loadtxt
from math import log, exp

values = loadtxt("values.txt", float)
logs = array(map(log, values, float))
geometric = exp(sum(logs) / len(logs))
print(geometric)

FileNotFoundError: [Errno 2] No such file or directory: 'values.txt'

### Note: need to use the function copy otherwise points to the same memory address

In [38]:
from numpy import copy
b = copy(a)

### Slicing

In [41]:
from numpy import array
r = array([1, 3, 5, 7, 9, 11, 13, 15],int)

print(r[2:5])

[5 7 9]


### Example 2.9 The Madelung constant -- Not finished

In [ ]:
from math import sqrt, pi

i = 0
j = 0
k = 0
epsilon0 = 1 #constant

a = 0 # spacing
pos = a * sqrt((i)**2 + (j)**2 + (k)**2)
potential = exp(1) / (4 * pi * epsilon0 * a)*pos

### Example Using Map

In [30]:
def sqr(x): return x**2
oldlist = [3, 4, 5]
print(list(map(sqr, oldlist)))

[9, 16, 25]
